### PR TITLE
Add back package metadata

### PR DESCRIPTION
**Pull request by isage**
After https://github.com/vitasdk/vdpm/pull/87

### CODE REVIEW

**Review by sharkwouter — CHANGES_REQUESTED** [review]
So I did a quick test with this and it seems there is still some errors. When trying to build SDL2 I see the following errors:
```

==> Creating package "sdl2"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
find: ‘/tmp/vdpm_install_’: No such file or directory
tar: option requires an argument -- 'f'
Try 'tar --help' or 'tar --usage' for more information.
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: sdl2 2.24.0-1 (Di 11. Okt 10:39:58 CEST 2022)
```

The package is still created and it contains `.BUILDINFO`, `.PKGINFO`, `.MTREE` and all other expected files.

The `.BUILDINFO` file looks like this, though:
```
builddir = /home/wouter/Personal/sdl2
pkgbuild_sha256sum = 7df584f43d8473b07f2b6c2b6cb97d46f2ef24d9e3cc0596ca0e74ebc6eccce2
buildenv = !distcc
buildenv = color
buildenv = !ccache
buildenv = check
buildenv = !sign
options = strip
options = docs
options = libtool
options = staticlibs
options = emptydirs
options = zipman
options = purge
options = !debug
installed = Installing-...
installed = Failed-to
installed = install,
installed = the
installed = package
installed = probably
installed = does
installed = not
installed = exist.
```
That last part seems a bit off.

I don't understand what the  `.MTREE` does or how it's used, but I the contents of it looks like this:
```
wouter@wouter-gridscale:~/Personal/sdl2$ bsdtar -tvf .MTREE
-rw-r--r--  0 0      0         532 Okt 11 10:39 ./.BUILDINFO
-rw-r--r--  0 0      0         252 Okt 11 10:39 ./.PKGINFO
drwxr-xr-x  0 0      0           0 Okt 11 10:39 ./bin
-rwxr-xr-x  0 0      0        1769 Okt 11 10:39 ./bin/sdl2-config
drwxr-xr-x  0 0      0           0 Okt 11 10:39 ./include
drwxr-xr-x  0 0      0           0 Okt 11 10:39 ./include/SDL2
-rw-r--r--  0 0      0        8084 Aug 19 17:44 ./include/SDL2/SDL.h
-rw-r--r--  0 0      0       12564 Aug 19 17:44 ./include/SDL2/SDL_assert.h
-rw-r--r--  0 0      0       14798 Aug 19 17:44 ./include/SDL2/SDL_atomic.h
-rw-r--r--  0 0      0       59694 Aug 19 17:44 ./include/SDL2/SDL_audio.h
-rw-r--r--  0 0      0        3205 Aug 19 17:44 ./include/SDL2/SDL_bits.h
-rw-r--r--  0 0      0        9047 Aug 19 17:44 ./include/SDL2/SDL_blendmode.h
-rw-r--r--  0 0      0        2792 Aug 19 17:44 ./include/SDL2/SDL_clipboard.h
-rw-r--r--  0 0      0       17450 Okt 11 10:39 ./include/SDL2/SDL_config.h
-rw-r--r--  0 0      0         939 Aug 19 17:44 ./include/SDL2/SDL_copying.h
-rw-r--r--  0 0      0       17431 Aug 19 17:44 ./include/SDL2/SDL_cpuinfo.h
-rw-r--r--  0 0      0      106377 Aug 19 17:44 ./include/SDL2/SDL_egl.h
-rw-r--r--  0 0      0        9802 Aug 19 17:44 ./include/SDL2/SDL_endian.h
-rw-r--r--  0 0      0        5177 Aug 19 17:44 ./include/SDL2/SDL_error.h
-rw-r--r--  0 0      0       46839 Aug 19 17:44 ./include/SDL2/SDL_events.h
-rw-r--r--  0 0      0        5320 Aug 19 17:44 ./include/SDL2/SDL_filesystem.h
-rw-r--r--  0 0      0       39151 Aug 19 17:44 ./include/SDL2/SDL_gamecontroller.h
-rw-r--r--  0 0      0        3418 Aug 19 17:44 ./include/SDL2/SDL_gesture.h
-rw-r--r--  0 0      0        3146 Aug 19 17:44 ./include/SDL2/SDL_guid.h
-rw-r--r--  0 0      0       43268 Aug 19 17:44 ./include/SDL2/SDL_haptic.h
-rw-r--r--  0 0      0       17842 Aug 19 17:44 ./include/SDL2/SDL_hidapi.h
-rw-r--r--  0 0      0      103506 Aug 19 17:44 ./include/SDL2/SDL_hints.h
-rw-r--r--  0 0      0       37730 Aug 19 17:44 ./include/SDL2/SDL_joystick.h
-rw-r--r--  0 0      0       11044 Aug 19 17:44 ./include/SDL2/SDL_keyboard.h
-rw-r--r--  0 0      0       15629 Aug 19 17:44 ./include/SDL2/SDL_keycode.h
-rw-r--r--  0 0      0        3908 Aug 19 17:44 ./include/SDL2/SDL_loadso.h
-rw-r--r--  0 0      0        3812 Aug 19 17:44 ./include/SDL2/SDL_locale.h
-rw-r--r--  0 0      0       11684 Aug 19 17:44 ./include/SDL2/SDL_log.h
-rw-r--r--  0 0      0        8607 Aug 19 17:44 ./include/SDL2/SDL_main.h
-rw-r--r--  0 0      0        6693 Aug 19 17:44 ./include/SDL2/SDL_messagebox.h
-rw-r--r--  0 0      0        3379 Aug 19 17:44 ./include/SDL2/SDL_metal.h
-rw-r--r--  0 0      0        2845 Aug 19 17:44 ./include/SDL2/SDL_misc.h
-rw-r--r--  0 0      0       17087 Aug 19 17:44 ./include/SDL2/SDL_mouse.h
-rw-r--r--  0 0      0       14286 Aug 19 17:44 ./include/SDL2/SDL_mutex.h
-rw-r--r--  0 0      0        1155 Aug 19 17:44 ./include/SDL2/SDL_name.h
-rw-r--r--  0 0      0       82593 Aug 19 17:44 ./include/SDL2/SDL_opengl.h
-rw-r--r--  0 0      0      731576 Aug 19 17:44 ./include/SDL2/SDL_opengl_glext.h
-rw-r--r--  0 0      0        1254 Aug 19 17:44 ./include/SDL2/SDL_opengles.h
-rw-r--r--  0 0      0        1606 Aug 19 17:44 ./include/SDL2/SDL_opengles2.h
-rw-r--r--  0 0      0       31876 Aug 19 17:44 ./include/SDL2/SDL_opengles2_gl2.h
-rw-r--r--  0 0      0       98695 Aug 19 17:44 ./include/SDL2/SDL_opengles2_gl2ext.h
-rw-r--r--  0 0      0         913 Aug 19 17:44 ./include/SDL2/SDL_opengles2_gl2platform.h
-rw-r--r--  0 0      0       10022 Aug 19 17:44 ./include/SDL2/SDL_opengles2_khrplatform.h
-rw-r--r--  0 0      0       24522 Aug 19 17:44 ./include/SDL2/SDL_pixels.h
-rw-r--r--  0 0      0        6682 Aug 19 17:44 ./include/SDL2/SDL_platform.h
-rw-r--r--  0 0      0        3199 Aug 19 17:44 ./include/SDL2/SDL_power.h
-rw-r--r--  0 0      0        2106 Aug 19 17:44 ./include/SDL2/SDL_quit.h
-rw-r--r--  0 0      0       12860 Aug 19 17:44 ./include/SDL2/SDL_rect.h
-rw-r--r--  0 0      0       73613 Aug 19 17:44 ./include/SDL2/SDL_render.h
-rw-r--r--  0 0      0         109 Okt 11 10:39 ./include/SDL2/SDL_revision.h
-rw-r--r--  0 0      0       28101 Aug 19 17:44 ./include/SDL2/SDL_rwops.h
-rw-r--r--  0 0      0       16206 Aug 19 17:44 ./include/SDL2/SDL_scancode.h
-rw-r--r--  0 0      0        9206 Aug 19 17:44 ./include/SDL2/SDL_sensor.h
-rw-r--r--  0 0      0        5904 Aug 19 17:44 ./include/SDL2/SDL_shape.h
-rw-r--r--  0 0      0       29407 Aug 19 17:44 ./include/SDL2/SDL_stdinc.h
-rw-r--r--  0 0      0       36798 Aug 19 17:44 ./include/SDL2/SDL_surface.h
-rw-r--r--  0 0      0       20772 Aug 19 17:44 ./include/SDL2/SDL_system.h
-rw-r--r--  0 0      0       11506 Aug 19 17:44 ./include/SDL2/SDL_syswm.h
-rw-r--r--  0 0      0        2000 Aug 19 17:44 ./include/SDL2/SDL_test.h
-rw-r--r--  0 0      0        3235 Aug 19 17:44 ./include/SDL2/SDL_test_assert.h
-rw-r--r--  0 0      0        6872 Aug 19 17:44 ./include/SDL2/SDL_test_common.h
-rw-r--r--  0 0      0        2163 Aug 19 17:44 ./include/SDL2/SDL_test_compare.h
-rw-r--r--  0 0      0        3385 Aug 19 17:44 ./include/SDL2/SDL_test_crc32.h
-rw-r--r--  0 0      0        5432 Aug 19 17:44 ./include/SDL2/SDL_test_font.h
-rw-r--r--  0 0      0       13203 Aug 19 17:44 ./include/SDL2/SDL_test_fuzzer.h
-rw-r--r--  0 0      0        4634 Aug 19 17:44 ./include/SDL2/SDL_test_harness.h
-rw-r--r--  0 0      0        2215 Aug 19 17:44 ./include/SDL2/SDL_test_images.h
-rw-r--r--  0 0      0        1954 Aug 19 17:44 ./include/SDL2/SDL_test_log.h
-rw-r--r--  0 0      0        4630 Aug 19 17:44 ./include/SDL2/SDL_test_md5.h
-rw-r--r--  0 0      0        1787 Aug 19 17:44 ./include/SDL2/SDL_test_memory.h
-rw-r--r--  0 0      0        3156 Aug 19 17:44 ./include/SDL2/SDL_test_random.h
-rw-r--r--  0 0      0       17250 Aug 19 17:44 ./include/SDL2/SDL_thread.h
-rw-r--r--  0 0      0        7290 Aug 19 17:44 ./include/SDL2/SDL_timer.h
-rw-r--r--  0 0      0        4506 Aug 19 17:44 ./include/SDL2/SDL_touch.h
-rw-r--r--  0 0      0        1031 Aug 19 17:44 ./include/SDL2/SDL_types.h
-rw-r--r--  0 0      0        6870 Aug 19 17:44 ./include/SDL2/SDL_version.h
-rw-r--r--  0 0      0       78952 Aug 19 17:44 ./include/SDL2/SDL_video.h
-rw-r--r--  0 0      0        8540 Aug 19 17:44 ./include/SDL2/SDL_vulkan.h
-rw-r--r--  0 0      0        5512 Aug 19 17:44 ./include/SDL2/begin_code.h
-rw-r--r--  0 0      0        1480 Aug 19 17:44 ./include/SDL2/close_code.h
drwxr-xr-x  0 0      0           0 Okt 11 10:39 ./lib
-rw-r--r--  0 0      0     1150616 Okt 11 10:39 ./lib/libSDL2.a
-rw-r--r--  0 0      0      248038 Okt 11 10:39 ./lib/libSDL2_test.a
-rw-r--r--  0 0      0         988 Okt 11 10:39 ./lib/libSDL2main.a
drwxr-xr-x  0 0      0           0 Okt 11 10:39 ./lib/cmake
drwxr-xr-x  0 0      0           0 Okt 11 10:39 ./lib/cmake/SDL2
-rw-r--r--  0 0      0        3079 Okt 11 10:39 ./lib/cmake/SDL2/SDL2Config.cmake
-rw-r--r--  0 0      0        1978 Okt 11 10:39 ./lib/cmake/SDL2/SDL2ConfigVersion.cmake
-rw-r--r--  0 0      0         833 Okt 11 10:39 ./lib/cmake/SDL2/SDL2mainTargets-release.cmake
-rw-r--r--  0 0      0        3291 Okt 11 10:39 ./lib/cmake/SDL2/SDL2mainTargets.cmake
-rw-r--r--  0 0      0         840 Okt 11 10:39 ./lib/cmake/SDL2/SDL2staticTargets-release.cmake
-rw-r--r--  0 0      0        4015 Okt 11 10:39 ./lib/cmake/SDL2/SDL2staticTargets.cmake
-rw-r--r--  0 0      0         835 Okt 11 10:39 ./lib/cmake/SDL2/SDL2testTargets-release.cmake
-rw-r--r--  0 0      0        3291 Okt 11 10:39 ./lib/cmake/SDL2/SDL2testTargets.cmake
drwxr-xr-x  0 0      0           0 Okt 11 10:39 ./lib/pkgconfig
-rw-r--r--  0 0      0         747 Okt 11 10:39 ./lib/pkgconfig/sdl2.pc
drwxr-xr-x  0 0      0           0 Okt 11 10:39 ./share
drwxr-xr-x  0 0      0           0 Okt 11 10:39 ./share/aclocal
-rw-r--r--  0 0      0        7775 Aug 19 17:44 ./share/aclocal/sdl2.m4
drwxr-xr-x  0 0      0           0 Okt 11 10:39 ./share/licenses
drwxr-xr-x  0 0      0           0 Okt 11 10:39 ./share/licenses/SDL2
-rw-r--r--  0 0      0         884 Aug 19 17:44 ./share/licenses/SDL2/LICENSE.txt
```
I'm testing this on Ubuntu 22.04.

**Comment by isage** [comment]
Closing, as i'm working on using proper upstream pacman

**Comment by sharkwouter** [comment]
> Closing, as i'm working on using proper upstream pacman

Maybe the implementation for this I made in PSPDEV could help you. You'll probably run into the same problems we did, which are addressed in the patch and the scripts: https://github.com/pspdev/psp-pacman

**Comment by isage** [comment]
Thx

**Pull request closed without merging**
